# python main.py recognition -c config/st_gcn/ntu-xsub/train_bone.yaml
#work_dir: data/st-gcn/xsub/bone/bone_1
work_dir: work_dir/ntu60/xsub/bone

# feeder
feeder: feeder.feeder_skeleton.Feeder
train_feeder_args:
  centralization: False
  random_move: False
  if_bone: False
  # path 수정 필요
  data_path: /home/irteam/dcloud-global-dir/NIAMoCap/Data/MMNet/ntu60_skeletons_preprocessed/xsub/train_data_bone.npy
  label_path: /home/irteam/dcloud-global-dir/NIAMoCap/Data/MMNet/ntu60_skeletons_preprocessed/xsub/train_label.pkl
test_feeder_args:
  centralization: False
  if_bone: False
  # path 수정 필요
  data_path: /home/irteam/dcloud-global-dir/NIAMoCap/Data/MMNet/ntu60_skeletons_preprocessed/xsub/val_data_bone.npy
  label_path: /home/irteam/dcloud-global-dir/NIAMoCap/Data/MMNet/ntu60_skeletons_preprocessed/xsub/val_label.pkl

# model
model: net.gcn.Model
model_args:
  in_channels: 3
  num_class: 60
  dropout: 0.5
  edge_importance_weighting: False  # 수정
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [10, 50]

# training
device: [0,1,2,3,4]
batch_size: 64
test_batch_size: 64
num_epoch: 80
